name: CI/CD Pipeline

# Trigger the workflow on push and pull requests to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Frontend Checks
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend  # Set default working directory for frontend jobs
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Check Types
        run: npm run typescript
        
      - name: Lint Check
        run: npm run lint
      
      - name: Run Tests
        run: npm test
        
      - name: Build Project
        run: npm run build

  backend:
    name: Backend Checks
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend  # Set default working directory for backend jobs
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: ./backend/package-lock.json
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Check Types
        run: npm run typescript
        
      - name: Lint Check
        run: npm run lint
      
      - name: Run Tests
        run: npm test